version: '3.8'

services:
  geoip:
    image: observabilitystack/geoip-api:latest
    restart: unless-stopped
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - geoip